MonAPI-xyz/MonAPI

- README.md
- sonar-project.properties
Update readme and sonar rule
Initiate backend
> chore(readme): update readme and sonar rule

- monapi/settings.py
Update insecure config debug 
Initiate backend
> chore(config): update insecure debug configuration

- .github/workflows/build.yml
- .github/workflows/production.yml
- .github/workflows/staging.yml
- .github/workflows/test.yml
- Makefile
- docs/development.md
- pull_request_template.md
- requirements.txt
- sonar-project.properties
Update github workflow and sonar properties
Initiate backend
- run sonar scan
- run test on all branch push
> [CHORE] update github workflow and sonar properties

- apimonitor/tests.py
Change unit test authentication to Token auth
[MON-47 Create view list API monitor backend](https://monapi.atlassian.net/browse/MON-47)
- User able to see all of API monitor already created by current user
- On each API monitor showed info such as API monitor name, path, success rate, response time
```
curl --location --request GET 'http://127.0.0.1:8000/monitor/'
```
```
[
{
"id": 1,
"name": "Test",
"method": "GET",
"url": "/test/",
"schedule": "1MIN",
"body_type": "EMPTY",
"query_params": [],
"headers": [],
"body_form": [],
"raw_body": [],
"success_rate": 50.0,
"avg_response_time": 100,
"success_rate_history": [
{
"date": "2022-09-19",
"hour": 20,
"minute": 0,
"success": 0,
"failed": 0
},
{
"date": "2022-09-19",
"hour": 21,
"minute": 0,
"success": 0,
"failed": 0
},
{
"date": …
```
> [TEST] change test authentication method

- monapi/settings.py
- requirements.txt
Update cors headers to allow request from frontend
[MON-8 Initiate project and repository](https://monapi.atlassian.net/browse/MON-8)
- CORS allowed on whitelisted url
> [CHORES] update cors headers

- login/admin.py
- login/apps.py
- login/models.py
- login/serializers.py
- login/tests.py
- login/urls.py
- login/utils.py
- login/views.py
- monapi/settings.py
- monapi/urls.py
Implement login endpoint
[MON-41 Create login backend](https://monapi.atlassian.net/browse/MON-41?atlOrigin=eyJpIjoiMmY5ZGFiZDczYThlNDVhZGEyZDIxOTQ1MDhjMmNhNTkiLCJwIjoiaiJ9)
- User able to login to their account by using email and password
> feat: PBI-2 login backend

- apimonitor/serializers.py
- apimonitor/tests.py
Update decimal field for list monitor
MON-47: Create view list API monitor backend
- Got 1 decimal points in success rate
```
[
{
"avg_response_time": 81,
"body_form": [
{
"id": 1,
"key": "Test Key Body",
"monitor": 1,
"value": "Test Value Body"
}
],
"body_type": "FORM",
"headers": [
{
"id": 1,
"key": "Test Key Header",
"monitor": 1,
"value": "Test Value Header"
}
],
"id": 1,
"method": "GET",
"name": "Test Monitor",
"query_params": [
{
"id": 1,
"key": "Test Key Query",
"monitor": 1,
"value": "Test Value Query"
}
],
"raw_body": [
{
"body": "Test Body",
"id": 1,
"monitor": 1
}
],
"schedule": "10MIN",
"success_rate": "75.0",
"success_rate_history": [
{
"date": "2022-09-19",
"failed": 0,
"hour": 11,
"minute": 0,
"success": 0
},
{
"date": "2022-09-19",
"failed": 0,
"hour": 12,
"minute": 0, …
```
> refactor: update decimal field list monitor

- error_logs/admin.py
- error_logs/apps.py
- error_logs/models.py
- error_logs/serializers.py
- error_logs/tests.py
- error_logs/urls.py
- error_logs/views.py
- monapi/settings.py
- monapi/urls.py
- Create test for error logs list and the detail
- Create the implementation for view error logs feature
[MON-57 View error log backend](https://monapi.atlassian.net/browse/MON-57)
- User can view error logs list  (execution time, api response, etc) of each failed API monitor
- User can view error log detail of a failed API monitor
List:
Detail:
> feat: PBI-12-View Error Logs-Backend

- README.md
- apimonitor/serializers.py
- cron/management/commands/run_cron.py
- cron/views.py
- docs/release_notes.md
Add cron decode error handler
[MON-17: Enable Cron API Monitor](https://monapi.atlassian.net/browse/MON-17)
- API Monitor run on configured interval on each API monitor
> refactor: add cron decode error handler

- error_logs/tests.py
- error_logs/views.py
- monapi/settings.py
- Adding pagination in global setting, and error logs
[MON-57 View error log backend](https://monapi.atlassian.net/browse/MON-57)
- Return list as pagination
> feat: PBI 12 view error logs backend

- cron/management/commands/run_cron.py
- cron/views.py
refactor: fine tuning cron delay
PBI-11: enable cron
- Cron can work properly on expected interval
```
```
> refactor: fine tuning cron delay

- cron/management/commands/run_cron.py
- cron/tests.py
- cron/views.py
Improve cron delay accuracy until +- 0.1 second
PBI-11: enable cron
- Cron run in expected interval
> feat: improve cron delay accuracy

- requirements.txt
chores: bump django version security cve
> chores: bump django version security cve

- alerts/admin.py
- alerts/apps.py
- alerts/models.py
- alerts/serializers.py
- alerts/tests.py
- alerts/urls.py
- alerts/views.py
- apimonitor/admin.py
- apimonitor/urls.py
- monapi/settings.py
- monapi/urls.py
Implement backend for alerts configuration
[MON-71: [BE] edit alert config + research](https://monapi.atlassian.net/browse/MON-71)
- User able to change alerts configurations
- User able to configure with the options, such as discord, pagerduty, email, and slack
Get Configuration
```
curl --location --request GET 'http://localhost:8000/alerts/config/' \
--header 'Authorization: Token 9f0e0e2e20831866b4b480e056bceee8375d0f6f'
```
```
{
"is_slack_active": false,
"slack_token": "",
"slack_channel_id": "",
"is_discord_active": false,
"discord_bot_token": "",
"discord_guild_id": "",
"discord_channel_id": "",
"is_pagerduty_active": false,
"pagerduty_api_key": "",
"pagerduty_default_from_email": "",
"is_email_active": false,
"email_host": "",
"email_port": null,
"email_username": "", …
```
> feat: PBI-18 alerts configuration

- monapi/settings.py
refactor: add sentry headers to cors
- Please copy acceptance criteria from backlog info
```
Put your API CURL and example response here
```
> refactor: add sentry headers to cors

- alerts/management/commands/run_cron_alerts.py
- template/email/alerts.html
Add new alert formats for all alerts
- User understand the alert message clearly
> refactor: add new alert formats for all alerts

- apitest/admin.py
- apitest/apps.py
- apitest/models.py
- apitest/serializers.py
- apitest/tests.py
- apitest/urls.py
- apitest/views.py
- monapi/settings.py
- monapi/urls.py
Implement api test
PBI-21-test_api-backend
- User can test API via API monitoring tools
- User can see response of API
```
curl --location --request POST 'localhost:8000/api-test/' \
--header 'Authorization: Token 82cfa4189bb7c8c2a4be30ef975e9b6e1f219ae7' \
--header 'Content-Type: application/json' \
--data-raw '{
"method": "GET",
"url": "https://api-staging.monapi.xyz/",
"body_type": "RAW",
"query_params": [
{
"key": "qp_key1",
"value": "qp_value1"
},
{
"key": "qp_key2",
"value": "qp_value2"
}
],
"headers": [
{
"key": "h_key1",
"value": "h_value1"
}
],
"body_form": "Doesn'\''t matter because body_type is RAW, can be None",
"raw_body": "Test raw body"
}'
```
```
{
"response": "{\"detail\":\"Authentication credentials were not provided.\"}"
}
```
> feat: Pbi 21 test api backend

- apimonitor/migrations/0014_remove_alertsconfiguration_user_and_more.py
- apimonitor/migrations/0015_alter_alertsconfiguration_team_alter_apimonitor_team.py
- login/tests.py
refactor: update migrations depedency
PBI-28: team authentication
- User able to login using user account and access to team data
- User able to change current session to another team
> refactor: update migrations depedency

- team_management/serializers.py
- team_management/tests.py
- team_management/views.py
Implement view current team profile backend
Pbi 25 view current team profile backend
- Please copy acceptance criteria from backlog info
```
curl --location --request GET 'localhost:8000/team-management/current/' \
--header 'Authorization: Token 3c8f298a25107c2d803d5f1f78d480425f2e4752'
```
```
{
"id": 2,
"name": "Ferdifadillah3",
"logo": null,
"description": "",
"teammember": [
2
]
}
```
> feat: Pbi 25 view current team profile backend

- apimonitor/views.py
- invite_team_members/admin.py
- invite_team_members/serializers.py
- invite_team_members/tests.py
- invite_team_members/views.py
- login/serializers.py
- login/tests.py
- login/urls.py
- login/utils.py
- login/views.py
- team_management/serializers.py
- team_management/tests.py
- Change parameter on invite team member to only `invited_email`, use team info from auth session
- Change parameter on cancel invite team member to only `user_id`, use team info from auth session
- Update response on endpoint `/team-management/current/` , add user id and verified status
- Update `/auth/available_team/` to only team with team member verified status
- Update `/auth/change_team/` to only able change to team with team member verified status
- Update `/auth/login/` to only able login to team with team member verified status
- Remove endpoint `/auth/list_member/` use `/team-management/current/` instead
- Fix security issue on update api monitor, restrict api monitor to only api monitor owned by same team
- Fix potential duplicate team member when invite team
- Fix potential …
> refactor: change security check on invite team member

- statuspage/serializers.py
- statuspage/views.py
refactor: change request process method to allow form
PBI-32: status page configuration
- User can configure path of API status page
- User can create category for status page
- User can delete category for status page
- User can change status page category of each API monitor
```
curl --location --request POST 'http://localhost:8000/status-page/category/' \
--header 'Authorization: Token c690b640c5ca60f8fcc066c3afe7f7f98e16adf6' \
--form 'name="new-category"'
```
> refactor: change request process method to allow form

- forget_password/admin.py
- register/admin.py
refactor: add admin for models verified user and forget password token
> refactor: add admin for models verified user and forget password token
